### ISSUE TITLE
Getting UNKNOWN: dm:[No devices to check]

### ISSUE THREAD

**Issue by R1-Limited** [glensc/nagios-plugin-check_raid#169] opened 2017-06-19 15:45 UTC
I could not find anyting pertaining to my issue so I am reporting in my CentOS 5 system running Nagios latest I am getting the UNKNOWN: dm:[No devices to check]

**Output of `check_raid -d`:**
```
/usr/lib64/nagios/plugins/check_raid.pl -d
check_raid 4.0.6
Visit <https://github.com/glensc/nagios-plugin-check_raid#reporting-bugs> how to report bugs

DEBUG EXEC: /sbin/dmraid -r at /usr/lib64/nagios/plugins/check_raid.pl line 482.
DEBUG EXEC: /proc/mdstat at /usr/lib64/nagios/plugins/check_raid.pl line 482.
DEBUG EXEC: /sbin/dmsetup status --noflush at /usr/lib64/nagios/plugins/check_raid.pl line 482.
DEBUG EXEC: /sbin/dmraid -r at /usr/lib64/nagios/plugins/check_raid.pl line 482.
OK: dm:[ddf1_Teo:AA]; dmraid:[.ddf1_disks: /dev/sda(GROUP, 931.26 MiB): ok, /dev/sdb(GROUP, 931.26 MiB): ok, /dev/sdc(GROUP, 931.26 MiB): ok]
```

```
[nagios@teomon.localdomain ~]$ /usr/local/nagios/libexec/check_nrpe -H 10.10.38.47 -t 30 -c check_raid 
UNKNOWN: dm:[No devices to check]
```

**Comment by glensc** [comment] 2017-06-19 16:17
like #142, duplicate of #138

**Comment by R1-Limited** [comment] 2017-06-19 16:29
NRPE: Unable to read output
prefex with sudo or su

**Comment by R1-Limited** [comment] 2017-06-19 19:23
I think what is going on is it is reading the Nagios Server and popping up with mo device ODD
[root@teomon libexec]# /usr/local/nagios/libexec/check_raid.pl
UNKNOWN: dm:[No devices to check]

this of course running at the nagios root.  Running from the target itself I get a proprt read.  

SO it appears that Nagios is running this against itself and not pushing to the target.. Hummmm

**Comment by R1-Limited** [comment] 2017-06-19 19:29
Never mind, I foudn the issue, user and group was not created... My Bad

**Comment by glensc** [comment] 2017-06-19 20:34
hitting "Close issue" button for you then

**Closed by glensc** 2017-06-19 20:34 UTC
Labels: dm, question
